version: '3.4'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 7238:7238
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:7238
    volumes:
      - .:/backend
    ports:
      - "7238:7238"