# Generated by Django 3.0.3 on 2021-05-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCarrousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='carrousel/')),
                ('url', models.CharField(max_length=200)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
