# Generated by Django 3.0.3 on 2022-02-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.RemoveField(
            model_name='address',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
    ]
