# Generated by Django 3.0.3 on 2021-05-24 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0002_auto_20210524_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='one_click_purchasing',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer_id',
        ),
    ]
